### ISSUE TITLE
test issues

### ISSUE THREAD

**Issue by rrazaghi** [nanoporetech/pychopper#3]
Hi,
not a huge deal but perhaps things changed during the last update. make test doesn't find pychopper script which can be solved by moving pychopper to the scripts folder.
Also I'm trying to use pinfish pipeline for my SQK-PCS-108 pcr_cdna analysis and was wondering if the barcode option is mandatory for pychopper on these datasets.

Thank you,
Roham

**Comment by bsipos** [comment]
Hello,

The test should be run after install, in which case the script should be already in the path. Try installing first and see if the problem persists.
Regarding SQK-PCS-108: yes, the barcode option is mandatory as it specifies primers rather than barcodes. Sorry for the terminological confusion, will correct this in the next release.

Regards,
Botond

**Comment by rrazaghi** [comment]
Thank you,
one last question regarding the PCS-108: 
https://community.nanoporetech.com/technical_documents/chemistry-technical-document/v/chtd_500_v1_revo_07jul2016/rna-sequencing-direct-and-via-cdna
from the link above I should input the forward and reverse cPRM as my barcode parameters, right?


Thanks again,
Roham

**Comment by bsipos** [comment]
Hi Roham,

Sorry for the late reply. You should use the strand switching primer (SSP) and the reverse complement of the reverse transcription primer (VNP). However, the document you linked is not up to date. Until is updated you can refer to [this file](https://github.com/nanoporetech/pychopper/blob/master/data/cdna_barcodes.fas).
Note that not all of the As are included from the VNP primer.

Best,
Botond

**Comment by bsipos** [comment]
FYI the page is updated now.
