### ISSUE TITLE
How to choose reads type to the downstream process?

### ISSUE THREAD

**Issue by huangziyan11111** [nanoporetech/pychopper#30]
Hi, I am processing the nanopore data for transcriptome analysis, I want to know that I need just use the reads_full_length.fq or I can use all the output reads (reads_full_length.fq + rescued.fq + unclassified.fq) to downstream analysis?
If I can use all the reads, the purpose of "cdna_classifier.py" is to trim the primer sequence, is that right?

**Comment by bsipos** [comment]
You only need the `reads_full_length.fq`.

**Comment by huangziyan11111** [comment]
Could you tell me why unclassified.fq can't be used？

**Comment by huangziyan11111** [comment]
> You only need the `reads_full_length.fq`.

Could you tell me why unclassified.fq can't be used？

**Comment by huangziyan11111** [comment]
@bsipos Could you tell me why unclassified.fq can't be used？

**Comment by bsipos** [comment]
Because they do not have one or both PCR primers identified. Hence they are not guaranteed to be full length *in sequencing* and their orientation cannot be determined.

**Comment by RogerioRibeiro201505534** [comment]
Hi there! This issue is already closed soo maybe I should make another one, but here it goes: 

I'm also using nanopore reads for transcriptomics analysis. For what I understood, the rescue_reads.fq are reads that had middle adaptors and were separated right? Why I should not use these when performing (re)annotation? What about quantification?
